// -*- C++ -*-
//
// generated by wxGlade 0.8.0 on Fri Apr 13 20:59:07 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOG_H
#define DIALOG_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
public:
	// begin wxGlade: MyFrame::ids
	// end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

	void OnExitDlg(wxCloseEvent& WXUNUSED(event));
	void OnStore(wxCommandEvent& event);
	void OnRestore(wxCommandEvent& event);
	void OnSave(wxCommandEvent & event);
	void OnLoad(wxCommandEvent & event);

private:
	// begin wxGlade: MyFrame::methods
	void set_properties();
	void do_layout();
	// end wxGlade

protected:
	// begin wxGlade: MyFrame::attributes
	wxButton* btnStore;
	wxButton* btnRestore;
	wxButton* btnSave;
	wxButton* btnLoad;
	// end wxGlade

}; // wxGlade: end class


#endif // DIALOG_H
