// -*- C++ -*-
//
// generated by wxGlade 0.8.0 on Sun Apr 15 23:27:14 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "warn_dlg.h"
#include <wx/stdpaths.h>
#include <wx/filename.h>

// begin wxGlade: ::extracode
// end wxGlade

WarnDlg::WarnDlg(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
	wxDialog(parent, id, title, pos, size, wxCLIP_CHILDREN|wxDEFAULT_DIALOG_STYLE)
{
	// begin wxGlade: WarnDlg::WarnDlg
	btnYes = new wxButton(this, wxID_ANY, wxT("Yes"));
	btnNo = new wxButton(this, wxID_ANY, wxT("No"));
	checkbox_1 = new wxCheckBox(this, wxID_ANY, wxT(" Dont ask me again"));

	set_properties();
	do_layout();
	// end wxGlade

	Connect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(WarnDlg::OnCloseDlg),NULL,this);

	btnYes->Bind(wxEVT_BUTTON, &WarnDlg::OnYes, this);
	btnNo->Bind(wxEVT_BUTTON, &WarnDlg::OnNo, this);

}


void WarnDlg::set_properties()
{
	// begin wxGlade: WarnDlg::set_properties
	SetTitle(wxT("Warning Layout already stored"));
	// end wxGlade
}


void WarnDlg::do_layout()
{
	wxStandardPaths::Get();
	wxString fileLocation = wxStandardPaths::Get().GetExecutablePath();
	fileLocation = wxFileName(fileLocation).GetPath();
	fileLocation = fileLocation + wxT("/MatStore/icons/warn-msg_32.png");
	// begin wxGlade: WarnDlg::do_layout
	wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
	wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
	wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(2, 3, 0, 0);
	grid_sizer_1->Add(50, 30, 1, wxEXPAND, 0);
	grid_sizer_1->Add(0, 0, 0, 0, 0);
	grid_sizer_1->Add(50, 30, 1, wxEXPAND, 0);
	wxStaticBitmap* bitmap_1 = new wxStaticBitmap(this, wxID_ANY, wxBitmap(fileLocation, wxBITMAP_TYPE_ANY));
	grid_sizer_1->Add(bitmap_1, 0, wxALIGN_RIGHT, 0);
	wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, wxT("You have already a stored material layout do you want to overwrite it?"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER|wxST_NO_AUTORESIZE);
	label_1->SetMinSize(wxSize(200, 35));
	grid_sizer_1->Add(label_1, 0, 0, 0);
	grid_sizer_1->Add(0, 0, 0, 0, 0);
	sizer_2->Add(grid_sizer_1, 0, wxBOTTOM, 30);
	sizer_3->Add(20, 20, 2, 0, 0);
	sizer_3->Add(btnYes, 0, wxALIGN_RIGHT|wxRIGHT, 10);
	sizer_3->Add(btnNo, 0, wxALIGN_RIGHT, 0);
	sizer_3->Add(20, 0, 0, 0, 0);
	sizer_2->Add(sizer_3, 1, wxBOTTOM|wxEXPAND, 15);
	sizer_2->Add(checkbox_1, 0, wxBOTTOM|wxLEFT, 10);
	SetSizer(sizer_2);
	sizer_2->Fit(this);
	Layout();
	Centre();
	// end wxGlade
}

void WarnDlg::OnCloseDlg(wxCloseEvent& event)
{
	if (this->IsModal())
		EndModal(retVal);
	else
		Close();
}

void WarnDlg::OnYes(wxCommandEvent & event)
{
	if (checkbox_1->GetValue())
		canshow = false;
	retVal = wxID_YES;
	this->Close();
}

void WarnDlg::OnNo(wxCommandEvent & event)
{
	if (checkbox_1->GetValue())
		canshow = true;
	retVal = wxID_NO;
	this->Close();
}

int WarnDlg::ShowDialog()
{
	if (canshow)
		return this->ShowModal();
	else
		return retVal;
}

